# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff603675e35067d1ce811e36307bb1a61ff3240e2c7264e1de4fa99fd7bfdfd8550145e4a0f4909e4be6214970558ef9e9835fd3d9c756182f35ceb9848d068

test:
  secret_key_base: 398ea20c614710d171f5e9d1429f42c48736a19aa2efeba8661f8b02931355119f26150a2bf375d84a4d9f501dbff5cf9f60b1344516f10f8aa2af482612444b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
